# -*- coding: utf-8 -*-
"""siata.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JUlOCJjskACzoIe6O0GzV10EcmWgRo9n

# 📊 Análisis de Calidad del Aire: PM2.5 (SIATA)

**Fuente de datos:** SIATA - Sistema de Alerta Temprana de Medellín y el Valle de Aburrá  
**Endpoint:** `https://siata.gov.co/EntregaData1/Datos_SIATA_Aire_AQ_pm25_Last.json`  

Este cuaderno descarga, limpia y visualiza los últimos datos de material particulado PM2.5 de la red oficial.
"""

# 1. Importar librerías necesarias
import requests
import pandas as pd
import matplotlib.pyplot as plt
import warnings

warnings.filterwarnings('ignore')

# 2. Definir la URL de la API
url = "https://siata.gov.co/EntregaData1/Datos_SIATA_Aire_AQ_pm25_Last.json"

print("⏳ Descargando datos desde SIATA...")
try:
    response = requests.get(url, headers={'User-Agent': 'Mozilla/5.0'})
    response.raise_for_status()
    datos_raw = response.json()
    print(f"✅ ¡Éxito! Se descargaron {len(datos_raw)} registros.")
except Exception as e:
    print(f"❌ Error al descargar los datos: {e}")

import pandas as pd
# 3. Convertir a DataFrame y limpiar los datos
df = pd.json_normalize(datos_raw, record_path='measurements')

# Filtrar valores nulos o códigos de error de SIATA (-9999 significa 'Dato No Disponible')
df_limpio = df[df['value'] != -9999].copy()

# Convertir columnas de fecha a formato datetime
df_limpio['date.local'] = pd.to_datetime(df_limpio['date.local'])
df_limpio['date.utc'] = pd.to_datetime(df_limpio['date.utc'])

# Convertir valor a numérico (por si acaso)
df_limpio['value'] = pd.to_numeric(df_limpio['value'], errors='coerce')

print(f"📊 Registros válidos después de la limpieza: {len(df_limpio)}")
display(df_limpio[['location', 'value', 'unit', 'date.local']].head(10))

# 4. Análisis Exploratorio: Promedio reciente por estación
# Agrupamos por ubicación y calculamos el promedio de PM2.5
resumen_estaciones = df_limpio.groupby('location').agg(
    Promedio_PM25=('value', 'mean'),
    Maximo_PM25=('value', 'max'),
    Mediciones=('value', 'count')
).reset_index().sort_values(by='Promedio_PM25', ascending=False)

print("📈 Top 10 estaciones con mayor concentración promedio de PM2.5:")
display(resumen_estaciones.head(10))

# 5. Visualización: Gráfico de barras de las estaciones con mayor promedio
plt.figure(figsize=(12, 6))
top_10 = resumen_estaciones.head(10)

bars = plt.barh(top_10['location'], top_10['Promedio_PM25'], color='salmon')
plt.xlabel('Concentración Promedio de PM2.5 (µg/m³)')
plt.title('Top 10 Estaciones con Mayor Concentración de PM2.5')
plt.gca().invert_yaxis() # Invertir para que la más alta quede arriba

# Añadir líneas de referencia de la OMS / Normativa (ej. 15 µg/m³ promedio anual OMS)
plt.axvline(x=15, color='red', linestyle='--', label='Límite OMS (15 µg/m³)')
plt.legend()

plt.tight_layout()
plt.show()

"""### 📖 Diccionario de Datos y Notas de Interpretación

| Columna | Descripción |
|---|---|
| `location` | Nombre y descripción de la estación de monitoreo. |
| `value` | Valor de la medición en **µg/m³**. |
| `date.local` | Fecha y hora en horario de Colombia (UTC-5). |
| `coordinates.latitude` / `longitude` | Ubicación geográfica de la estación. |

**⚠️ Notas importantes:**
1. El valor **`-9999`** es el código estándar de SIATA para "Dato No Disponible" (mantenimiento, calibración o falla del sensor). Este cuaderno ya los filtra automáticamente.
2. Un promedio de PM2.5 superior a **15 µg/m³** (anual) o **45 µg/m³** (24 horas) supera las recomendaciones de la OMS y la normativa colombiana, representando un riesgo para la salud.
"""